### ISSUE TITLE
setup conflicts 

### ISSUE THREAD

**Issue by dancinglightning** [jasontruluck/tmdb_rexx#6]
that was quick :-( , when installing the gem it wants to install a program setup. Way to general name, rename to setup_rexx ?

gem install 'tmdb_rexx'
Fetching: faraday_middleware-0.10.0.gem (100%)
Successfully installed faraday_middleware-0.10.0
Fetching: tmdb_rexx-0.6.0.gem (100%)
tmdb_rexx's executable "setup" conflicts with factory_girl_rails
Overwrite the executable? [yN]  n
ERROR:  Error installing tmdb_rexx:

Not that factory girl should have a setup binary (noone should).

**Comment by jasontruluck** [comment]
@dancinglightning thanks for catching this I have not come across this yet. I suspect it is from [this](https://github.com/jasontruluck/tmdb_rexx/blob/b9a9408c01759b216352f78d5cab12c31dac503b/spec/spec_helper.rb#L13) which I definitely agree is too general. An update for this should be coming soon.

**Comment by jasontruluck** [comment]
This should be fixed with the new release. Please let me know if you still have any issues.
